name: Deployment staging

concurrency: staging

on:
  push:
    branches: [ dev ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    needs: build
    steps:
      - name: deploy