name: Deployment production

concurrency: production

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - name: deploy