name: Deployment staging

on:
  push:
    branches: [ dev ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy
        uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present