on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  test:
    name: Test unitaire
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
  security:
    name: Test de sécurité
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          output: security.txt
      - if: always()
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: security report
          path: security.txt
        retention-days: 5
  sonarcloud:
    name: Test de qualité
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
      # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=theodeniaud
            -Dsonar.projectKey=theodeniaud_project_DevOps
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}